name = "cf-worker-ws-dev" # todo
#name = "cf-worker-connect-test" # todo
#main = "test/worker/cf-cdn-cgi-trace2.js"
#main = "test/worker/worker-connect-test.js"
main = "_worker.js"
compatibility_date = "2023-05-26"

[vars]
# UUID = "ceaa32fb-a54b-49ca-93a7-6fa7a2a6d94f"
# PROXYIP = "1.2.3.4"
# DNS_RESOLVER_URL = "https://cloudflare-dns.com/dns-query"
# NODE_ID = "1"
# API_TOKEN = "example_dev_token"
# API_HOST = "api.v2board.com"
UUID = '55a057cb-10c3-4a64-bd7a-c0dd20cf9557"
